### ISSUE TITLE
Komponenta README, commit ID:954544d6d36cbcbad83c393a412f6e338c5adc12, Nema opisa za pokretanje aplikacije na Windows sistemima

### ISSUE THREAD

**Issue by Chosa** [SoftverInzenjeringETFSA/SI2016_TIM3#1]
<img width="298" alt="nemaopisa1" src="https://cloud.githubusercontent.com/assets/26483398/26760591/9e9403e8-491d-11e7-9e01-9e3087302e30.PNG">
<img width="536" alt="nemaopisa2" src="https://cloud.githubusercontent.com/assets/26483398/26760592/a0b0a29e-491d-11e7-8f09-b8bbdff3e382.PNG">
<img width="518" alt="nemaopisa3" src="https://cloud.githubusercontent.com/assets/26483398/26760594/a23a5a4c-491d-11e7-9b4d-4ee917613c19.PNG">

**Comment by Chosa** [comment]
1.Skrolati se do Opisa Readme.
2.Pročitati..
3.Zaključak, nema opisa za pokretanje aplikacije na windows sistemima.
4.Očekivani rezultat, da se nađe upustvo za pokretanje na windows sistemima.

**Comment by epajic16747** [comment]
Dodan je opis za windows
