### ISSUE TITLE
Komponenta: Kreiranje eventa, commit ID 1cc97dc5df416eece6bcd54ee80eaa30742fcd3c, OPIS: Neispravno prikazivanje unešenih podataka nakon kreiranja eventa.

### ISSUE THREAD

**Issue by Chosa** [SoftverInzenjeringETFSA/SI2016_TIM3#10]
1.Nakon uspješne prijave
2.Klik na Kreiraj Event
3.Popunjavanje naziva eventa pod: Saša Matić
4.Popunjavanje ostalih podataka
5.Klik na dugme Kreiraj Event
6.Event se kreira ali sa sljedećim nazivom: Saša Mati?
7.Očekivano je bilo da naziv bude: Saša Matić
<img width="548" alt="regbezob2" src="https://cloud.githubusercontent.com/assets/26483398/26761149/a6907d30-492a-11e7-9914-caa54279b9fc.PNG">
<img width="540" alt="sasamatic" src="https://cloud.githubusercontent.com/assets/26483398/26761154/c577e738-492a-11e7-9192-4338ae0e1f48.PNG">
<img width="414" alt="neispravnoprezime" src="https://cloud.githubusercontent.com/assets/26483398/26761166/e2f3f202-492a-11e7-8d0c-27b68a21ea91.PNG">

**Comment by ohri31** [comment]
U pitanju su postavke baze podataka na okruženju. Ukoliko nije postavljen utf-8 encoding, dešavat će se ova greška. Obzirom da se radi o aspektu koji nije u nadležnosti development time, već u nadležnosti lokalne konfiguracije servera, ovdje se ne radi o bug-u.

**
![image](https://user-images.githubusercontent.com/5159759/26981366-28c4593a-4d35-11e7-8c57-d6651e16ae76.png)
**
