### ISSUE TITLE
Komponenta: Pozivani korisnici, commit ID 1cc97dc5df416eece6bcd54ee80eaa30742fcd3c,OPIS:Nakon pozvanog korisnika na već kreirani event,Dugme prijavi korisnika se ne ponaša kako treba.

### ISSUE THREAD

**Issue by Chosa** [SoftverInzenjeringETFSA/SI2016_TIM3#11]
Koraci
1.Prijavimo se 
2.Klik na dugme Kreiraj event
3.Popunimo polja
4.Klik na dugme Kreiraj event
5.Preko polja pozovite korisnika, pozovemo korisnika na event
6.Klik na dugme: prijavi korisnika
7.Klik na: OK bez popunjavanja polja
8.Dolazi obavještenje da je korisnik prijavljen
9.Očekivano ponašanje je bilo da se ne može  kliknuti dugme Ok bez popunjavanja
<img width="416" alt="dugme prijavi" src="https://cloud.githubusercontent.com/assets/26483398/26761772/55ea5aac-4936-11e7-8487-3ababeafef9f.PNG">
<img width="339" alt="dugme prijavi2" src="https://cloud.githubusercontent.com/assets/26483398/26761777/5f7e5208-4936-11e7-8380-fe69e9b6004a.PNG">
<img width="298" alt="dugme prijavi 3" src="https://cloud.githubusercontent.com/assets/26483398/26761780/645888e8-4936-11e7-9d38-6bc319fca5ea.PNG">

**Comment by ohri31** [comment]
Fixed. Napravljena obavijest da se mora unijeti razlog.
