### ISSUE TITLE
Brisanje eventa

### ISSUE THREAD

**Issue by scatic1** [SoftverInzenjeringETFSA/SI2016_TIM3#14]
Opis problema: Nakon što korisnik izbriše event koji je kreirao, svi ostali eventi koji su u njegovom vlasništvu se ne prikazuju.

Koraci za reprodukciju problema:
Pokrenuti aplikaciju
Prijaviti se
Kliknuti na  "Moji eventi"
Izabrati željeni event i izbrisati ga
Kliknuti na "Moji eventi"

Dobijeni rezultat: Neispisani eventi (Slika 2)
Očekivani rezultat: Prikazivanje svih evenata koji nisu izbrisani a u vlasništvu su logovanog korisnika

![moj-event](https://cloud.githubusercontent.com/assets/17402989/26762700/bcf9333e-4946-11e7-90fc-b45781833e9d.jpg)

Nakon brisanja eventa "Moj event":

![poslije-brisanja](https://cloud.githubusercontent.com/assets/17402989/26762702/ca0ee9a6-4946-11e7-870e-35e636ac5c63.jpg)

**Comment by ohri31** [comment]
Fixed
