### ISSUE TITLE
Komponenta: Registracija korisnika, commit ID: c9fd682217f157920aa4a6801e9c55d58048004c, Opis:Neusaglašenost SRS-a i funkcionalnih zahtjeva prilikom registracije,nema poruke o uspješnoj registraciji.

### ISSUE THREAD

**Issue by Chosa** [SoftverInzenjeringETFSA/SI2016_TIM3#2]
<img width="423" alt="obavjestenjeoregistraciji" src="https://cloud.githubusercontent.com/assets/26483398/26760634/6b4fec12-491e-11e7-9136-dbdf2750cf66.PNG">

**Comment by Chosa** [comment]
1.Unos podataka u odgovarajuća polja
2.Klik na dugme Registruj se
3.Nema obavještenja o uspješnoj registraciji
<img width="425" alt="regisracijabezob1" src="https://cloud.githubusercontent.com/assets/26483398/26760876/2838da4c-4923-11e7-963d-9a4130e37714.PNG">

**Comment by Chosa** [comment]
<img width="548" alt="regbezob2" src="https://cloud.githubusercontent.com/assets/26483398/26760981/9794f06c-4926-11e7-9a4a-b3bae9e1d6e6.PNG">

**Comment by mirzamushic** [comment]
![uspjesnaregistracija](https://user-images.githubusercontent.com/17408021/26888169-7a676bb0-4baa-11e7-8354-bc14ae2ed0ae.jpg)
