### ISSUE TITLE
Komponenta:Registracija novog korisnika, commit ID:c9fd682217f157920aa4a6801e9c55d58048004c, Opis:Omogućeno je prihavatanje nevalidne email adrese ( Omerver@etf.unsa.ba.com.com) u polju za emial adresu

### ISSUE THREAD

**Issue by Chosa** [SoftverInzenjeringETFSA/SI2016_TIM3#3]
Komponenta:Registracija novog korisnika, commit ID:c9fd682217f157920aa4a6801e9c55d58048004c,
Opis:Omogućeno je prihavatanje nevalidne email adrese (Omerver@etf.unsa.ba.com.com )
u polju za emial adresu.
<img width="414" alt="validacijamaila" src="https://cloud.githubusercontent.com/assets/26483398/26760997/11deffc0-4927-11e7-84b9-e46a5e4b5308.PNG">

**Comment by Chosa** [comment]
1.Upisivanje imena i prezimena.
2.Upis nevalidne email adrese  Omerver@etf.unsa.ba.com.com
3.Upis šifre.
4.Klik na dugme Registruj me.
5.Prihavata se registracija a nebi trebala.
6.Očekivano je odbijanje registracije.

**Comment by Chosa** [comment]
<img width="548" alt="regbezob2" src="https://cloud.githubusercontent.com/assets/26483398/26761002/4b09f4e4-4927-11e7-9973-aa64e4050767.PNG">

**Comment by epajic16747** [comment]
U SRS-u je specificirano da samo da polje email nije prazno. Pored toga ima validacija na adekvatni format. 

![image](https://cloud.githubusercontent.com/assets/17408033/26762472/3e4353e2-4943-11e7-8d73-9521659d2e9f.png)
