### ISSUE TITLE
Komponenta: Registarcija novog eventa, commit ID: 1cc97dc5df416eece6bcd54ee80eaa30742fcd3c, Opis: Omogućeno je da se prijavljuje na evente nakon vremena dešavanja samog eventa.

### ISSUE THREAD

**Issue by eceric31** [SoftverInzenjeringETFSA/SI2016_TIM3#4]
![deadline za prijave iza vremena eventa](https://cloud.githubusercontent.com/assets/16662438/26760305/2420741e-4915-11e7-91fa-d44e7ae3c183.PNG)

**Comment by eceric31** [comment]
Koraci: 1. Login (ukoliko je korisnik registrovan)
            2. Klik na dugme kreiraj event
            3. Unos odgovarajućih vrijednosti u polja (vrijeme održavanja prije vremena roka za prijave)
            4. Klik na dugme kreiraj event

**Comment by epajic16747** [comment]
Slika nije adekvatna

**Comment by eceric31** [comment]
Očekivani rezultat - ispis greške prilikom registracije korisnika
Dobijeni rezultat - uspješna registracija korisnika
