### ISSUE TITLE
Komponenta: Registracija korisnika, commitID: c9fd682217f157920aa4a6801e9c55d58048004c, Opis: Prilikom unošenja već postojeće mail adrese nemoguće je registrovati korisnika, pri čemu se ne ispisuje nikakva greška.

### ISSUE THREAD

**Issue by eceric31** [SoftverInzenjeringETFSA/SI2016_TIM3#6]
![onemogucena registracija te nema ispisa greske](https://cloud.githubusercontent.com/assets/16662438/26760403/45221e7c-4917-11e7-99c8-639100b399bf.PNG)

**Comment by eceric31** [comment]
Koraci: 1. Klik na dugme za registraciju
2. Unos odgovarajućih vrijednosti u polja (postojeća mail adresa)
3. Klik na dugme registruj se

**Comment by eceric31** [comment]
Očekivani rezultat - ispis greške prilikom registracije korisnika
Dobijeni rezultat - stanje se ne mijenja, bez registracije ili ispisa greške

**Comment by ohri31** [comment]
Fixed.

****

![image](https://user-images.githubusercontent.com/5159759/26981879-cd50bc7c-4d36-11e7-9d48-4d9c01b2ec70.png)
