### ISSUE TITLE
Komponenta: Registarcija novog eventa, commit ID: 1cc97dc5df416eece6bcd54ee80eaa30742fcd3c, Opis: Prihvatanje nevalidnih vrijednosti prilikom registracije eventa.

### ISSUE THREAD

**Issue by eceric31** [SoftverInzenjeringETFSA/SI2016_TIM3#9]
![greseke prilikom prihvatanja nevalidnih vrijednosti pri prijavi eventa](https://cloud.githubusercontent.com/assets/16662438/26760477/3be221ac-4919-11e7-8629-5f409975344c.PNG)

**Comment by eceric31** [comment]
Koraci: 1. Login (ukoliko je korisnik registrovan)
            2. Klik na dugme kreiraj event
            3. Unos odgovarajućih vrijednosti u polja
            4. Klik na dugme kreiraj event

**Comment by eceric31** [comment]
Očekivani rezultat - sprječavanje registracije eventa uz ispis greške pri unosu nekorektnih vrijednosti
Dobijeni rezultat - uspješno registrovan event

**Comment by ohri31** [comment]
@epajic16747 Fixed? 

![image](https://user-images.githubusercontent.com/5159759/26981407-4a28b440-4d35-11e7-8286-6b1ccf4734c8.png)

**Comment by epajic16747** [comment]
Jest
